spring.application.name=user-service
server.port=8088

spring.main.allow-bean-definition-overriding=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/usersdb
spring.datasource.username=postgres
spring.datasource.password=denis

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

kafka.topic=t.notification
kafka.consumer.group-id=my-group

producer.properties.max.block.ms=5000
producer.properties.request.timeout.ms=3000
producer.properties.delivery.timeout.ms=10000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true