spring:
  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082

kafka:
  topic: t.notification
  consumer:
    group-id: my-group

from:
  email: example@gmail.com